[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Cache-control para archivos HTML
  for = "*.html"
    [headers.values]
      Cache-Control = "public, max-age=0, must-revalidate"

  # Cache-control para archivos estáticos (CSS, JS, imágenes, etc.)
  for = "/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000, immutable"
